from pathlib import Path
import base64, json, re, sys

root = Path(sys.argv[1])
project = root / "ThreeOneOSFive"
assets = project / "Assets.xcassets"
repo_assets = Path(__file__).resolve().parent.parent / "assets"

def install_imageset(name: str, source_name: str):
    target = assets / f"{name}.imageset"
    target.mkdir(parents=True, exist_ok=True)
    dst_name = f"{name}.jpg"
    payload = (repo_assets / source_name).read_text().strip()
    (target / dst_name).write_bytes(base64.b64decode(payload))
    contents = {
        "images": [
            {"filename": dst_name, "idiom": "universal", "scale": "1x"},
            {"idiom": "universal", "scale": "2x"},
            {"idiom": "universal", "scale": "3x"},
        ],
        "info": {"author": "xcode", "version": 1},
    }
    (target / "Contents.json").write_text(json.dumps(contents, indent=2) + "\n")

install_imageset("FreeFireIcon", "FreeFireIcon.b64")
install_imageset("FreeFireMaxIcon", "FreeFireMaxIcon.b64")

# Shared game artwork view.
design = project / "views" / "DesignSystem.swift"
s = design.read_text()
if "struct HTVGameIcon: View" not in s:
    insert = r'''
struct HTVGameIcon: View {
    let game: String
    var size: CGFloat = 44

    private var assetName: String {
        game.lowercased() == "ffmax" ? "FreeFireMaxIcon" : "FreeFireIcon"
    }

    var body: some View {
        Image(assetName)
            .resizable()
            .scaledToFill()
            .frame(width: size, height: size)
            .clipShape(RoundedRectangle(cornerRadius: size * 0.24, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: size * 0.24, style: .continuous)
                    .stroke(AppTheme.accent.opacity(0.26), lineWidth: 1)
            )
            .shadow(color: AppTheme.accent.opacity(0.14), radius: 8, y: 3)
            .accessibilityHidden(true)
    }
}

'''
    anchor = "struct AppLogo: View {"
    if anchor not in s:
        raise RuntimeError("DesignSystem AppLogo anchor not found")
    s = s.replace(anchor, insert + anchor, 1)
design.write_text(s)

# Home game cards: use the supplied game artwork instead of SF Symbols.
home = project / "views" / "RepositoryHomeView.swift"
s = home.read_text()
s = s.replace('''                                systemImage: "scope",\n                                game: "ff",''',
              '''                                game: "ff",''', 1)
s = s.replace('''                                systemImage: "bolt.shield.fill",\n                                game: "ffmax",''',
              '''                                game: "ffmax",''', 1)
s = s.replace('''        systemImage: String,\n        game: String,''',
              '''        game: String,''', 1)

pattern = re.compile(r'''                    ZStack \{\n                        RoundedRectangle\(cornerRadius: 18, style: \.continuous\)\n                            \.fill\(\n                                LinearGradient\(\n                                    colors: \[AppTheme\.accent\.opacity\(0\.22\), AppTheme\.accent\.opacity\(0\.07\)\],\n                                    startPoint: \.topLeading,\n                                    endPoint: \.bottomTrailing\n                                \)\n                            \)\n                            \.frame\(width: 62, height: 62\)\n                        Image\(systemName: systemImage\)\n                            \.font\(\.system\(size: 26, weight: \.black\)\)\n                            \.foregroundStyle\(AppTheme\.accent\)\n                    \}''')
s, n = pattern.subn('                    HTVGameIcon(game: game, size: 62)', s, count=1)
if n == 0 and "HTVGameIcon(game: game, size: 62)" not in s:
    raise RuntimeError("Home game icon block not found")
home.write_text(s)

# Patch list cards: show the actual game artwork on both pending and ready rows.
patch = project / "views" / "PatchProjectsView.swift"
s = patch.read_text()

# Pending row may be base UI V2 or the retry/error UI generated by another build patch.
pending_start = s.find("    private func serverPendingRow")
pending_end = s.find("    @ViewBuilder\n    private func serverPatchRow", pending_start)
if pending_start < 0 or pending_end < 0:
    raise RuntimeError("serverPendingRow range not found")
pending = s[pending_start:pending_end]
pending = re.sub(
    r'''            AppRowIcon\(\n                systemName: failure == nil \? "arrow\.down\.circle\.fill" : "exclamationmark\.triangle\.fill",\n                tint: failure == nil \? AppTheme\.accent : \.orange,\n                frameSize: 42\n            \)''',
    '            HTVGameIcon(game: remote.game ?? "ff", size: 42)',
    pending,
    count=1,
)
pending = pending.replace('            AppRowIcon(systemName: "arrow.down.circle.fill", frameSize: 42)',
                          '            HTVGameIcon(game: remote.game ?? "ff", size: 42)', 1)
s = s[:pending_start] + pending + s[pending_end:]

row_start = s.find("    private func serverPatchRow")
row_end = s.find("\n    @ViewBuilder", row_start + 20)
if row_start < 0:
    raise RuntimeError("serverPatchRow not found")
if row_end < 0:
    row_end = s.find("\n    private func", row_start + 20)
row = s[row_start:row_end]
row = re.sub(
    r'''                AppRowIcon\(\n                    systemName: isActive \? "bolt\.shield\.fill" : "shippingbox\.fill",\n                    tint: isActive \? \.green : AppTheme\.accent,\n                    symbolSize: 19,\n                    frameSize: 44\n                \)''',
    '                HTVGameIcon(game: remote.game ?? "ff", size: 44)',
    row,
    count=1,
)
if 'HTVGameIcon(game: remote.game ?? "ff", size: 44)' not in row:
    raise RuntimeError("serverPatchRow icon block not found")
s = s[:row_start] + row + s[row_end:]
patch.write_text(s)

print("UI V2 Free Fire artwork installed in Home and patch cards")
